on:
  release:
    types:
      - created
jobs:
  releases-control:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos:
          - linux
          - windows
        goarch:
          - amd64
          - arm64
        exclude:
          - goarch: "386"
            goos: darwin
          - goarch: arm64
            goos: windows
    steps:
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          project_path: ./wieserlabs/cmd
          binary_name: flexdds